version: 2
jobs:

  setup:
    docker:
     - image: haxe:3.4
       environment:
          HAXE_VERSION: 3.4
    steps:
     - checkout
     - run: haxelib dev openfl openfl
     - run: if [[ $CIRCLE_BRANCH == 'master' ]]; then git clone -b master --single-branch --recursive https://github.com/openfl/lime ~/lime --depth 1 > log.txt || cat log.txt ; fi
     - run: if [[ $CIRCLE_BRANCH != 'master' ]]; then git clone -b develop --single-branch --recursive https://github.com/openfl/lime ~/lime --depth 1 > log.txt || cat log.txt ; fi
     - run: haxelib dev lime ~/lime
     - run: haxelib install compiletime
     - run: haxelib install hxcpp > log.txt || cat log.txt
     - run: if [[ $HAXE_VERSION != 'development' ]]; then yes | haxelib install hxcpp > log.txt || cat log.txt ; fi
     - run: if [[ $HAXE_VERSION == 'development' ]]; then git clone https://github.com/haxefoundation/hxcpp ~/hxcpp --depth 1 > log.txt || cat log.txt ; fi
     - run: if [[ $HAXE_VERSION == 'development' ]]; then haxelib dev hxcpp ~/hxcpp ; fi
     - run: if [[ $HAXE_VERSION == 'development' ]]; then cd ~/hxcpp/tools/hxcpp && haxe compile.hxml ; fi
     - run: if [[ $HAXE_VERSION == 'development' ]]; then cd ~/hxcpp/project && neko build.n linux-m64 ; fi
     - run: yes | haxelib install format > log.txt || cat log.txt
     - run: yes | haxelib install mcover > log.txt || cat log.txt
     - run: yes | haxelib install hamcrest > log.txt || cat log.txt
     - run: git clone https://github.com/jgranick/MassiveUnit ~/munit --depth 1 > log.txt || cat log.txt
     - run: haxelib dev munit ~/munit/src
     - run: cd ~/munit/tool
     - run: haxe build.hxml
     - run: haxelib run lime rebuild linux -release -64 -nocffi > log.txt || cat log.txt
     - run: haxelib run lime rebuild tools -nocffi
     - run: cd ~/openfl/tests/unit
     - run: haxelib run munit gen
  
  flash:
    docker:
     - image: haxe:3.4
    steps:
     - run: haxelib run munit test -as3 -norun -nocffi
  
  neko:
    docker:
     - image: haxe:3.4
    steps:
     - run: haxelib run lime build neko -nocffi
     - run: haxelib run lime build neko -Ddisable-cffi -nocffi
  
  html5:
    docker:
     - image: haxe:3.4
    steps:
     - run: haxelib run munit test -browser phantomjs -nocffi
  
  cpp:
    docker:
     - image: haxe:3.4
    steps:
     - run: haxelib run lime test linux --window-hardware=false
  
  docs:
    docker:
     - image: haxe:3.4
    steps:
     - run: git clone https://github.com/openfl/dox ~/dox --depth 1 > log.txt || cat log.txt
     - run: haxelib dev dox ~/dox
     - run: cd ~/openfl/docs && haxe build.hxml

workflows:
  version: 2
  test:
    jobs:
      - setup
      - flash:
          requires:
           - setup
      - neko:
          requires:
           - setup
      - html5:
          requires:
           - setup
      - cpp:
          requires:
           - setup
      - docs:
          requires:
           - setup